blank_issues_enabled: true
contact_links:
  - name: ğŸ§‘â€ğŸ’» Usage Problem
    url: https://github.com/lukasmasuch/streamlit-pydantic/discussions/new?category=q-a
    about: Do you have problems with usage and none of the suggestions in the docs helped?
  - name: â“ Anything else?
    url: https://github.com/lukasmasuch/streamlit-pydantic/discussions
    about: Do you have any other question?
